### ISSUE TITLE
Keep time

### ISSUE THREAD

**Issue by thejeshgn** [stefanocudini/gpx-simplify-optimizer#10]
The time goes missing once the track is simplified. Can we keep the timestamp?

**Comment by stefanocudini** [comment]
I think so, if you try so solve it in a fork I can suppot you... but sorry Now I don't have more free time

**Comment by stefanocudini** [comment]
@Wilkins might be interested

**Comment by Wilkins** [comment]
Hi  @thejeshgn 
Could you be more explicit with this issue ? Maybe you have an example of a sample file somewhere ?
Because I don't have timestamps in my track files.
Thanks.

**Comment by thejeshgn** [comment]
@Wilkins 
Example file: https://thejeshgn.com/blog/wp-content/uploads/2015/07/2015-07-08-car-hubballi-bangalore.gpx 

By default every point is
```
<trkpt lat="13.004387" lon="77.618395">
	<ele>937.45</ele>
	<time>2015-06-04T23:50:18Z</time>
	<pdop>3.20</pdop>
	<extensions>
		<gpxtpx:TrackPointExtension>
			<gpxtpx:course>312.67</gpxtpx:course>
		</gpxtpx:TrackPointExtension>
	</extensions>
</trkpt>
```

but after simplification it loses time

**Comment by thejeshgn** [comment]
@stefanocudini I understand, thank you, its a great tool
@Wilkins Thank you.

**Comment by Wilkins** [comment]
@thejeshgn, I looked into this issue.
It seems that the upload feature from Leaflet loose the time data and all other data excepted coordinates.
Leaflet converts the uploaded GPX file into GeoJSON raw data and only keep longitutde/latitude coordinates.
I have to look into this more deeply but it seems this is not a simple feature to add to this project...

**Comment by stefanocudini** [comment]
supporting it for all formats may be is not cheap idea.
But only for GPX input and GPX output can be useful.
One simple way  I'm thinking now is indexing lat,lon and time from input file and reuse its informations to putting in the output gpx files.. after the simplify

**Comment by Wilkins** [comment]
Yeah, I thought of that. But we will have to do it for all the GPX data : ele, pdop, course etc...
I'll try that for a first try, and @thejeshgn will tell us if it's ok for him.

**Comment by thejeshgn** [comment]
@Wilkins sure. I have huge gpx files from my recent trip for testing.

**Comment by Wilkins** [comment]
Well, it seems to be harder than this...
The Leaflet.FileLayer plugin that handle the GPX upload loose the data on upload. I opened an issue on the project to have help on this : https://github.com/makinacorpus/Leaflet.FileLayer/issues/20

If this way is a dead-end, we can think about a workaround with deeper modifications by changing the file loader plugin with this one : https://github.com/mpetazzoni/leaflet-gpx

**Comment by Wilkins** [comment]
Hi @thejeshgn, could you please test this new version with time support ?

**Comment by buzden** [comment]
Well, while the original issue author keeps silence, I can say (while using your wonderful tool) that it does not preserve time for points from original GPX files. Actually, I can say that when I'm trying to save simplified track with GeoJSON format, it seems to preserve elevation. But when saving as GPX, the tool does preverse neither elevation nor time.

By the way, the current toGeoJSON saves the times of points in GeoJSON as "coordTimes" array in the properties of the whole track, not like GPX (which saves time of a point as a property of this point). Maybe, this prevents from preserving time when saving optimized track back to GPX.

**Comment by Wilkins** [comment]
Humm, interesting. I must have messed up something in my tests or in my merge.
Could you please provide me some of your tests file in different formats (geojson and GPX) ? Please be careful of protecting your privacy and remove any private data from the files since they will be publicly readable.
Thank you.

**Comment by buzden** [comment]
[Here is an example](https://github.com/stefanocudini/gpx-simplify-optimizer/files/696520/missing-time.zip). The original file is a slightly cut GPX file got from a Garmin device which writes both time and elevation for each track point.

By the way, you can see what is done with UTF-8 string in the name of the track (it is written in Russian).
And, you also can seen that additional XML schemas (with possible additional Garmin info, like track color and etc., which were removed by hand but could left too) were also deleted during this resaving.

**Comment by Wilkins** [comment]
Thank you for the example. I will look into it at the end of january.

**Comment by Wilkins** [comment]
Issue fixed. But @stefanocudini 's version is not up to date on http://labs.easyblog.it/maps/gpx-simplify-optimizer/
@stefanocudini Could you please update your website ?

Otherwise, people can use the optimizer with this feature on my public copy : http://wilkins.fr/gpx/ 
NB: This is a working copy so things might get broken sometimes...

**Comment by stefanocudini** [comment]
thank you @Wilkins The online version is updated!!

I'm sorry but in the last month I was very busy looking for a new job :-/
