### ISSUE TITLE
It errors on KMLs with more than one boundary

### ISSUE THREAD

**Issue by freejoe76** [stefanocudini/gpx-simplify-optimizer#12]
Nova Scotia contains multiple islands, and when it's uploaded to the web interface ( http://labs.easyblog.it/maps/gpx-simplify-optimizer/?setLng=en ) the shapes are not manipulable. One-boundary KML's show up with blue fills, multiple-boundary KMLs show up with red fills.

To test this you may have to change the extension to kml.
[nova-scotia.txt](https://github.com/stefanocudini/gpx-simplify-optimizer/files/47837/nova-scotia.txt)

**Comment by Wilkins** [comment]
Issue confirmed.
I will try to look at it quickly to see what I can do about it.
Thanks.

**Comment by stefanocudini** [comment]
This tool is thinked for support only tipical gpx track.. 
But in the future may be support any type of gemotry

**Comment by freejoe76** [comment]
@stefanocudini Thanks for looking at it.

**Comment by Wilkins** [comment]
Hi @freejoe76,
I tried working on this issue. I manage to hack the actual mechanism to avoid the errors.
So you can import your nova-scotia KML file and simplify it.
But I still have issues :
- I had to convert "Polygon" to "LineString". It looks the same on the map, but when exporting to KML/GeoJSON it's still marked as "LineString". I had the error "Error: Invalid LatLng object: (NaN, NaN)" when calling the Leaflet GeoJSON.addData() method with Polygons
- When your KML is loaded, it is splitted in 7 LineString, and the 7 LineString can be simplfied together. But you can't hide/show them. Only the last Polygon is hideable/showable.

You can try it here for now : http://wilkins.fr/gpx/

I'll try to fix the remaining issues soon.

**Comment by freejoe76** [comment]
@Wilkins wow, I wasn't expecting that. Thank you~~~~~

**Comment by Wilkins** [comment]
@stefanocudini Can you reopen this please ?

**Comment by stefanocudini** [comment]
sure!

**Comment by Wilkins** [comment]
@freejoe76 Can you confirm this issue is closed ?

**Comment by freejoe76** [comment]
@Wilkins Confirmed. Going to dig into how you did this next. Thanks!
