### ISSUE TITLE
error in js libs

### ISSUE THREAD

**Issue by stefanocudini** [stefanocudini/gpx-simplify-optimizer#19]
@Wilkins I'm updated online vesion.. but the last update cause some problem about libs:
http://labs.easyblog.it/maps/gpx-simplify-optimizer/

**Comment by Wilkins** [comment]
Indeed... I'll look into it shortly. Sorry about that.

**Comment by Wilkins** [comment]
@stefanocudini The problem I found was because I changed the zoom to « 20 » which is too much. I will change it back.
What « error » do you see in JS libs ?

**Comment by stefanocudini** [comment]
I'm changed intial setview
