### ISSUE TITLE
More reduction / double pass

### ISSUE THREAD

**Issue by Wilkins** [stefanocudini/gpx-simplify-optimizer#2]
Hi,

I found your GPX path optimizer and I loved it ! http://labs.easyblog.it/maps/gpx-simplify-optimizer/
I'm trying to trace paths of my vacations, and to make it very small.
I created GPX file for the path from Las Vegas, NV to Tusayan AZ with the wonderful OSRM tool (http://map.project-osrm.org/)

But the generated file is very precise with about 2200 points.
I used your tool and narrowed it down to 220 points, which is already awesome.
I wanted to narrow it a second time, let's say to have 22 points or something.

The export format from your tool use `<trk>` and `<trkpt>` tags, although my gpx file has `<rte>` and `<rtept>`. I don't really know the difference between the 2 formats, but I rewrote the result file with rte/rtept tags. Your optimizer recognized well my new file, but I can't seem to optimize it more.
Is there a way to optimize it more ? Or maybe the optimization algorithm you use doesn't allow to degrade the path too much ?

Thank you for your time, and for your tool.
I discovered both OSRM and your optimizer the same week, and using both is going to be awesome for me ! 
Have a nice day !

**Comment by Wilkins** [comment]
Hi,

I'm answering to myself.
I was able to do what I wanted, I installed your project, and modified the following : 
in main.js
```
max: 0.1, //(instead of 0.002)
```
The result is great and my output file can be really tiny.
After that, I rebuild the minified JS : 
```
grunt
```

I hope this can help somebody.

Thank you !

**Comment by stefanocudini** [comment]
great!
