### ISSUE TITLE
Slider for filesize reduction does not show up

### ISSUE THREAD

**Issue by borreffm** [stefanocudini/gpx-simplify-optimizer#29]
I have been using GPX Optimizer since 2018 several times, but for some time now the app does not show the filesize reduction slider anymore, ie it does not work anymore. Tried it on different Win10 PCs with different browsers. The gpx-file upload works and the track is shown on the map.
Any idea what is going wrong ?
And: thanks for this great piece of software !

**Comment by stefanclark** [comment]
the last commit changed the css include in `index.html` from `dist/style.min.css` to `dist/style.css` - change it back and the slider re-appears

**Comment by stefanocudini** [comment]
solved
