### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Wilkins** [stefanocudini/gpx-simplify-optimizer#5]
Hi,

What is the license of this repository ?

Thanks

**Comment by stefanocudini** [comment]
I have yet to decide about it.
what do you advise me?

**Comment by Wilkins** [comment]
I'm more a GPLv2 or GPLv3 kinda guy... But as long as it is free software, I'm quite open about it :-)

**Comment by stefanocudini** [comment]
I'm just added MIT LICENSE file
