### ISSUE TITLE
remove diqus

### ISSUE THREAD

**Issue by stefanocudini** [stefanocudini/gpx-simplify-optimizer#8]
I was thinking we diqus is useless .. maybe I delete it altogether

@Wilkins  things do you think about it?

**Comment by Wilkins** [comment]
Hi,

I didn't know about disqus before, and I don't use it.
Plus it takes all the space on the screen.
So yeah you can remove it, it's fine for me.

Do you want me to remove it, or do you want to do it ?

**Comment by stefanocudini** [comment]
no ok I will remove it

I just wanted an opinion to convince me to do it :)
